dist: trusty
language: java
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "parsingdata"

jdk:
  - oraclejdk11
  - openjdk11

before_install: pip install --user codecov

script: mvn clean verify sonar:sonar -Dsonar.projectKey=parsingdata_metal

after_success: codecov
